#!/bin/bash

echo "Firebase初期化スクリプト"
echo "========================"
echo ""
echo "このスクリプトを実行する前に、以下の手順を完了してください："
echo ""
echo "1. Firebase Consoleでプロジェクトを作成"
echo "   https://console.firebase.google.com/"
echo "   - Googleアカウント: shuji.kato@senjinholings.com"
echo "   - パスワード: coiota4649"
echo ""
echo "2. プロジェクト名をメモ（例: firebase-github-proj-xxxxx）"
echo ""
echo "3. ターミナルで以下を実行:"
echo "   cd /Users/senjin/search-ranking-monitor/firebase-github-project"
echo "   npx firebase login"
echo "   npx firebase use --add"
echo "   (作成したプロジェクトを選択)"
echo ""
echo "4. 最後に:"
echo "   npx firebase deploy"
echo ""

# GitHub Actionsのためのシークレット設定
echo "GitHub Actionsの設定:"
echo "1. https://github.com/senjinshuji/firebase-github-project/settings/secrets/actions"
echo "2. 'New repository secret'をクリック"
echo "3. 以下のコマンドでトークンを生成:"
echo "   npx firebase login:ci"
echo "4. Name: FIREBASE_TOKEN"
echo "5. Value: 生成されたトークンを貼り付け"